feature: allow skipping corrupt TFRecords
aws/sagemaker-tensorflow-extensions pull request #120
Opened 2021-02-22 05:49 UTC by ishaaq

We've noticed records failing CRC checks very intermittently (tests
demonstrate one in 645 million TFRecords failing these CRC checks).

We've been unable to find the root cause for these failures but as a
workaround we're adding a new parameter: `max_corrupted_records_to_skip`
which will allow the pipe reader to skip these occasional corrupted
records without failing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-22 17:01 UTC, owen-t submitted a review, later dismissed

2021-02-22 22:11 UTC, ajaykarpur requested changes
Looks like `flake8` failed. Can you please address these violations?
```
./src/sagemaker_tensorflow/pipemode.py:44:121: E501 line too long (132 > 120 characters)
./src/sagemaker_tensorflow/pipemode.py:88:121: E501 line too long (132 > 120 characters)
```

2021-02-23 17:39 UTC, ajaykarpur requested changes
Looks like `cpplint` failed this time:
```
src/pipemode_op/Dataset/src/pipemode_dataset_op_kernel.cpp:180:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
src/pipemode_op/RecordReader/TFRecordReader.cpp:56:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
src/pipemode_op/RecordReader/TFRecordReader.hpp:33:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
src/pipemode_op/test/testRecordReader/TestTFRecordReader.cpp:37:  Lines should be <= 120 characters long  [whitespace/line_length] [2]
src/pipemode_op/test/testRecordReader/TestTFRecordReader.cpp:152:  Could not find a newline character at the end of the file.  [whitespace/ending_newline] [5]
```

2021-02-23 18:58 UTC, ajaykarpur approved these changes

2021-02-23 18:58 UTC, merged